# Generated by Django 5.1.3 on 2024-12-07 07:05

import MuseumApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('position', models.SmallIntegerField(choices=[(0, 'Запасник'), (1, 'Первый этаж'), (2, 'Второй этаж'), (3, 'Третий этаж'), (4, 'Другой музей')], default=None, verbose_name='Размещение')),
                ('on_restoration', models.BooleanField(default=False, verbose_name='На рестоврации')),
                ('open', models.BooleanField(default=False, verbose_name='Открыта')),
            ],
            options={
                'verbose_name': 'экспозиция',
                'verbose_name_plural': 'Экспозиции',
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('placement', models.ForeignKey(default=MuseumApp.models.Exposition.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exhibit', to='MuseumApp.exposition')),
            ],
            options={
                'verbose_name': 'экспонат',
                'verbose_name_plural': 'Экспонаты',
            },
        ),
    ]
